services:
  agenda.mq:
    container_name: "agenda.mq"
    image: rabbitmq:3.11.7-management
    environment:
      - RABBIT_DEFAULT_USER=guest
      - RABBIT_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
      - '15692:15692'
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    entrypoint: /bin/sh -c "rabbitmq-plugins enable rabbitmq_prometheus && rabbitmq-server"

  mailhog:
    container_name: "mailhog"
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: "sqlserver"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=fiap12345$
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"

  agenda.fiap:
    container_name: "agenda.fiap"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5207:80' 
    volumes:
      - ./src/App/appsettings.json:/app/appsettings.json
    environment:
      - ASPNETCORE_ENVIRONMENT=production
    depends_on:
      - agenda.mq
      - mailhog
      - sqlserver