services:
  agenda.mq:
    container_name: "agenda.mq"
    image: rabbitmq:3.11.7-management
    environment:
      - RABBIT_DEFAULT_USER=guest
      - RABBIT_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
      - '15692:15692'
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    entrypoint: /bin/sh -c "rabbitmq-plugins enable rabbitmq_prometheus && rabbitmq-server"