{
 "title": "Agenda Fiap",
 "description": "Monitoramento Api Agenda Fiap",
 "tags": [
  ".net",
  "agenda-fiap"
 ],
 "time": { "from": "2024-09-13T11:57:11.136Z", "to": "2024-09-13T12:02:06.424Z" },
 "templating": {
  "list": [
   {
    "name": "intervalo",
    "label": "Intervalo",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Agenda API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tempo de request por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(endpoint) (increase(http_request_duration_seconds_sum{job=\"agenda-fiap\"}[$intervalo]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total de Request com erro",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum by(code) (increase(http_request_duration_seconds_count{job=\"agenda-fiap\", code!~\"200|307|201|204\"}[$intervalo]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (up{job=\"agenda-fiap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantidade de Requests ativos por metodo",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_request_method) (microsoft_aspnetcore_hosting_http_server_active_requests{job=\"agenda-fiap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantidade de memoria alocada(MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (dotnet_total_memory_bytes{job=\"agenda-fiap\"}) / 1048576",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU utilizada",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (system_runtime_cpu_usage{job=\"agenda-fiap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RabbitMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total de Mensagens Lidas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantidade de Publicadores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_global_publishers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantidade de Conexões",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_connection_channels)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filas Criadas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(rabbitmq_queues_created_total[60s])) * on(job) rabbitmq_identity_info{job=\"RabbitMQ\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filas Removidas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(rabbitmq_queues_deleted_total[60s])) * on(job) rabbitmq_identity_info{job=\"RabbitMQ\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Mensagens não reconhecidas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channel_messages_unacked)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantidade de Consumidores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rabbitmq_consumers)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Quantidade de Filas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rabbitmq_queues)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total memoria usada",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rabbitmq_resident_memory_limit_bytes{job=\"RabbitMQ\"} * on(instance, job) rabbitmq_identity_info{job=\"RabbitMQ\"} - (rabbitmq_process_resident_memory_bytes{job=\"RabbitMQ\"} * on(instance, job) rabbitmq_identity_info{job=\"RabbitMQ\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Tamanho médio mensagens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(job) (rabbitmq_queue_messages_unacked_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}