apiVersion: v1
kind: Service
metadata:
  name: agenda-mq
spec:
  type: NodePort
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
      nodePort: 30001
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
      nodePort: 30011
    - name: prometheus
      port: 15692
      targetPort: 15692
      protocol: TCP
      nodePort: 30012
  selector:
    app: agenda-mq