name: Continuous integration

on:
  push:
    branches:
      - master
    pull_request:
      - master

    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore src/.
      
      - name: Build solution
        run: dotnet build src/.
      
      - name: List available tests
        run: dotnet test -t src/.
      
      - name: Test
        run: dotnet test src/.